services:
  backend:
    platform: linux/amd64
    build:
      context: ./api
      dockerfile: infra/php/Dockerfile.prod
      args:
        AWS_REGION: ${AWS_REGION}
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${PROJECT_NAME}-backend:${IMAGE_TAG}
    environment:
      # アプリケーション設定
      APP_NAME: ${PROJECT_NAME}
      APP_ENV: production
      APP_KEY: ${APP_KEY}
      APP_DEBUG: "false"
      LOG_CHANNEL: stderr
      APP_URL: https://api.${DOMAIN_NAME}
      LOG_LEVEL: error

      # データベース設定
      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST}
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_CONNECTION_RETRIES: 5
      DB_CONNECTION_RETRY_DELAY: 5
      WAIT_HOSTS: ${DB_HOST}:3306
      WAIT_HOSTS_TIMEOUT: 300

      # Broadcast/WebSocket設定
      BROADCAST_DRIVER: pusher
      PUSHER_APP_ID: ${PUSHER_APP_ID}
      PUSHER_APP_KEY: ${PUSHER_APP_KEY}
      PUSHER_APP_SECRET: ${PUSHER_APP_SECRET}
      PUSHER_HOST: api-ap3.pusher.com
      PUSHER_PORT: 443
      PUSHER_SCHEME: https
      PUSHER_APP_CLUSTER: ${PUSHER_APP_CLUSTER}
      PUSHER_DEBUG: "false"

      # Laravel WebSockets設定
      LARAVEL_WEBSOCKETS_ENABLED: "true"
      LARAVEL_WEBSOCKETS_HOST: 0.0.0.0
      LARAVEL_WEBSOCKETS_PORT: 6001
      LARAVEL_WEBSOCKETS_SCHEME: http
      LARAVEL_WEBSOCKETS_DEBUG: "false"

      # JWT設定
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGO: HS256

      # フロントエンドURL
      FRONTEND_URL: https://front.${DOMAIN_NAME}

      # その他の設定
      RUN_WEBSOCKETS: "true"
      AWS_USE_FIPS_ENDPOINT: "true"
      ECS_ENABLE_EXECUTE_COMMAND: "true"

  frontend:
    platform: linux/amd64
    build:
      context: ./front
      dockerfile: Dockerfile.prod
      args:
        NODE_ENV: production
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${PROJECT_NAME}-frontend:${IMAGE_TAG}
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_APP_ENV: production
      NEXT_PUBLIC_API_URL: https://api.${DOMAIN_NAME}
      NEXT_PUBLIC_PUSHER_APP_KEY: ${PUSHER_APP_KEY}
      NEXT_PUBLIC_PUSHER_HOST: api.${DOMAIN_NAME}
      NEXT_PUBLIC_PUSHER_PORT: 443
      NEXT_PUBLIC_PUSHER_SCHEME: https
      NEXT_PUBLIC_PUSHER_APP_CLUSTER: ${PUSHER_APP_CLUSTER}
      NEXT_PUBLIC_WEBSOCKET_HOST: api.${DOMAIN_NAME}
      NEXT_PUBLIC_WEBSOCKET_PORT: 443

networks:
  app-network:
    driver: bridge
