services:
  backend:
    platform: linux/amd64
    build:
      context: ./api
      dockerfile: infra/php/Dockerfile.prod
      args:
        AWS_REGION: ${AWS_REGION}
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${PROJECT_NAME}-backend:${IMAGE_TAG}
    environment:
      # アプリケーション設定（非機密情報のみ）
      APP_NAME: ${PROJECT_NAME}
      APP_ENV: production
      APP_DEBUG: "false"
      LOG_CHANNEL: stderr
      APP_URL: https://api.${DOMAIN_NAME}
      LOG_LEVEL: error

      # データベース基本設定（非機密情報のみ）
      DB_CONNECTION: mysql
      DB_PORT: 3306
      DB_CONNECTION_RETRIES: 5
      DB_CONNECTION_RETRY_DELAY: 5
      WAIT_HOSTS: ${DB_HOST}:3306
      WAIT_HOSTS_TIMEOUT: 300

      # Broadcast/WebSocket設定（非機密情報のみ）
      BROADCAST_DRIVER: pusher
      PUSHER_HOST: api-ap3.pusher.com
      PUSHER_PORT: 443
      PUSHER_SCHEME: https
      PUSHER_APP_CLUSTER: ${PUSHER_APP_CLUSTER}

      # Laravel WebSockets設定
      LARAVEL_WEBSOCKETS_ENABLED: "true"
      LARAVEL_WEBSOCKETS_HOST: 0.0.0.0
      LARAVEL_WEBSOCKETS_PORT: 6001
      LARAVEL_WEBSOCKETS_SCHEME: http
      LARAVEL_WEBSOCKETS_DEBUG: "false"

      # JWT基本設定（非機密情報のみ）
      JWT_ALGO: HS256
      JWT_TTL: 5

      # フロントエンドURL
      FRONTEND_URL: https://front.${DOMAIN_NAME}

      # その他の設定
      RUN_WEBSOCKETS: "true"
      AWS_USE_FIPS_ENDPOINT: "true"
      ECS_ENABLE_EXECUTE_COMMAND: "true"

      # AWS認証情報（Secrets Manager接続用）
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_REGION}

  frontend:
    platform: linux/amd64
    build:
      context: ./front
      dockerfile: Dockerfile.prod
      args:
        NODE_ENV: production
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${PROJECT_NAME}-frontend:${IMAGE_TAG}
    environment:
      # 基本設定（非機密情報）
      NODE_ENV: production
      NEXT_PUBLIC_APP_ENV: production

      # API接続設定（非機密情報）
      NEXT_PUBLIC_API_URL: https://api.${DOMAIN_NAME}

      # WebSocket接続設定（非機密情報）
      NEXT_PUBLIC_PUSHER_HOST: api.${DOMAIN_NAME}
      NEXT_PUBLIC_PUSHER_PORT: 443
      NEXT_PUBLIC_PUSHER_SCHEME: https
      NEXT_PUBLIC_PUSHER_APP_CLUSTER: ${PUSHER_APP_CLUSTER}
      NEXT_PUBLIC_WEBSOCKET_HOST: api.${DOMAIN_NAME}
      NEXT_PUBLIC_WEBSOCKET_PORT: 443

networks:
  app-network:
    driver: bridge
