services:
  app:
    build: ./api/infra/php
    volumes:
      - ./api/src:/data

  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./api/src:/data
      - ./api/infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data

  db:
    build: ./api/infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 33060:3306

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"

volumes:
  db-store:
