networks:
  app-network:
    driver: bridge

services:
  api:
    build: ./api/infra/php
    volumes:
      - ./api/src:/data
    environment:
      - RUN_WEBSOCKETS=true
    ports:
      - "6001:6001"
    depends_on:
      - db
    networks:
      - app-network

  web:
    image: nginx:1.20-alpine
    ports:
      - "8080:80"
    volumes:
      - ./api/src:/data
      - ./api/infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data
    depends_on:
      - api
    networks:
      - app-network

  db:
    build: ./api/infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 33060:3306
    networks:
      - app-network

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    networks:
      - app-network

volumes:
  db-store:
