version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.1
      - image: mysql:8.0
        environment:
          MYSQL_DATABASE: laravel
          MYSQL_USER: phper
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
          TZ: Asia/Tokyo
      - image: cimg/node:18.0

    working_directory: ~/project

    steps:
      - checkout

      # PHP dependencies
      - run:
          name: Install PHP dependencies
          working_directory: ./api
          command: |
            apt-get update && \
            apt-get -y install --no-install-recommends git unzip libzip-dev libicu-dev libonig-dev sqlite3 libsqlite3-dev && \
            curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
            pecl install xdebug && docker-php-ext-enable xdebug && \
            apt-get install -y nodejs && \
            apt-get clean && \
            rm -rf /var/lib/apt/lists/* && \
            docker-php-ext-install intl pdo_mysql zip bcmath pdo_sqlite && \
            composer install --prefer-dist --no-interaction

      # Set up database
      - run:
          name: Set up Database
          working_directory: ./api
          command: |
            cp .env.example .env
            php artisan key:generate
            php artisan migrate --force

      # Run Laravel tests
      - run:
          name: Run API Tests
          working_directory: ./api
          command: php artisan test

      # Node.js dependencies
      - run:
          name: Install Node.js dependencies
          working_directory: ./front
          command: npm install

      # Run Next.js tests
      - run:
          name: Run Frontend Tests
          working_directory: ./front
          command: npm run test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
