version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:8.1-cli
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
      - image: circleci/node:16
      - image: circleci/mysql:5.7

    working_directory: ~/project

    steps:
      - checkout

      # PHP dependencies
      - run:
          name: Install PHP dependencies
          working_directory: ./api
          command: |
            sudo apt-get update
            sudo apt-get install -y libpng-dev
            sudo docker-php-ext-install gd
            composer install --prefer-dist --no-interaction

      # Set up database
      - run:
          name: Set up Database
          working_directory: ./api
          command: |
            cp .env.example .env
            php artisan key:generate
            php artisan migrate --force

      # Run Laravel tests
      - run:
          name: Run API Tests
          working_directory: ./api
          command: php artisan test

      # Node.js dependencies
      - run:
          name: Install Node.js dependencies
          working_directory: ./front
          command: npm install

      # Run Next.js tests
      - run:
          name: Run Frontend Tests
          working_directory: ./front
          command: npm run test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
