version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    machine:
      image: ubuntu-2204:current

    steps:
      - checkout:
          submodules: false

      # SSHキーの追加
      - add_ssh_keys:
          fingerprints:
            - "${CI_SSH_FINGERPRINT_ROOT}"
            - "${CI_SSH_FINGERPRINT_API}"
            - "${CI_SSH_FINGERPRINT_FRONT}"

      - run:
          name: Configure SSH for GitHub
          command: |
            mkdir -p ~/.ssh
            echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            chmod 600 ~/.ssh/config

      - run:
          name: Generate .env file
          command: |
            # 必要なディレクトリが存在するか確認し、なければ作成
            if [ ! -d "~/project/api/src" ]; then
              mkdir -p ~/project/api/src
            fi

            # .envファイルを生成
            echo "APP_NAME=Laravel" > ~/project/api/src/.env
            echo "APP_ENV=local" >> ~/project/api/src/.env
            echo "APP_KEY=base64:9xUWuBizQZVJJoA2PRtuOIl3RuVicVln14GSlHZ96iY=" >> ~/project/api/src/.env
            echo "APP_DEBUG=true" >> ~/project/api/src/.env
            echo "APP_URL=http://localhost" >> ~/project/api/src/.env

            # Pusher関連の設定を環境変数から追加
            echo "PUSHER_APP_ID=${PUSHER_APP_ID}" >> ~/project/api/src/.env
            echo "PUSHER_APP_KEY=${PUSHER_APP_KEY}" >> ~/project/api/src/.env
            echo "PUSHER_APP_SECRET=${PUSHER_APP_SECRET}" >> ~/project/api/src/.env
            echo "PUSHER_HOST=${PUSHER_HOST}" >> ~/project/api/src/.env
            echo "PUSHER_PORT=${PUSHER_PORT}" >> ~/project/api/src/.env
            echo "PUSHER_SCHEME=${PUSHER_SCHEME}" >> ~/project/api/src/.env
            echo "PUSHER_APP_CLUSTER=${PUSHER_APP_CLUSTER}" >> ~/project/api/src/.env

            # データベースの設定を追加
            echo "DB_CONNECTION=mysql" >> ~/project/api/src/.env
            echo "DB_HOST=127.0.0.1" >> ~/project/api/src/.env
            echo "DB_PORT=3306" >> ~/project/api/src/.env
            echo "DB_DATABASE=${CI_MYSQL_DATABASE}" >> ~/project/api/src/.env
            echo "DB_USERNAME=${CI_MYSQL_USER}" >> ~/project/api/src/.env
            echo "DB_PASSWORD=${CI_MYSQL_PASSWORD}" >> ~/project/api/src/.env

            # その他の設定を追加
            echo "CACHE_DRIVER=file" >> ~/project/api/src/.env
            echo "QUEUE_CONNECTION=sync" >> ~/project/api/src/.env
            echo "SESSION_DRIVER=file" >> ~/project/api/src/.env

      # .envファイルの確認 (デバッグ用)
      - run:
          name: Check .env file
          command: cat ~/project/api/src/.env

      # 必要なパッケージのインストールやビルド
      - run:
          name: Install Composer Dependencies
          command: |
            cd ~/project/api/src
            composer install --no-interaction --prefer-dist

      - run:
          name: Install Node.js dependencies
          working_directory: ~/project/front
          command: |
            npm install

      # テストの実行
      - run:
          name: Run Laravel tests
          command: |
            cd ~/project/api/src
            php artisan test

      - run:
          name: Run frontend tests
          working_directory: ~/project/front
          command: |
            npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: my-context
